# Generated by Django 5.1.5 on 2025-01-15 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('dbAccountCode', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('dbAcctType', models.CharField(max_length=20)),
                ('dbAccount', models.CharField(max_length=100)),
                ('dbBalance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('dbAccountStatus', models.CharField(max_length=1)),
                ('dbEMail', models.CharField(blank=True, max_length=100, null=True)),
                ('dbTelNo', models.CharField(blank=True, max_length=20, null=True)),
                ('dbCelNo', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('dbAcctType', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('dbAcctDesc', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AV',
            fields=[
                ('dbAVNo', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('dbOwnerCode', models.CharField(max_length=20)),
                ('dbVType', models.CharField(max_length=50)),
                ('dbOTBaseWidth', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dbWTrack', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dbMass', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dbPayloadLimit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dbPayloadFactor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dbHtLimit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dbSpeedLimit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dbChkTruck', models.BooleanField()),
                ('dbChkOffRoad', models.BooleanField()),
                ('dbChkCond', models.BooleanField()),
                ('dbChkSteer', models.BooleanField()),
                ('dbBM_Ratio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dbSF_Ratio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='AV_BlockedRegNo',
            fields=[
                ('dbRegNo', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('dbReason', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Constant',
            fields=[
                ('dbFinYear', models.IntegerField()),
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('dbProvCode', models.CharField(max_length=10)),
                ('dbConstValue', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='ConstantsDescription',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('dbConstName', models.CharField(max_length=50)),
                ('dbConstDesc', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Embargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dbFromDate', models.DateField()),
                ('dbToDate', models.DateField()),
                ('dbEmbDesc', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EmbargoString',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dbPermitNo', models.IntegerField()),
                ('dbAmendNo', models.IntegerField()),
                ('dbEmbargoDate', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Escort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dbPermitNo', models.IntegerField()),
                ('dbAmendNo', models.IntegerField()),
                ('dbFromKm', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dbToKm', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dbEscortType', models.CharField(max_length=50)),
                ('dbNumEscorts', models.IntegerField()),
                ('dbWeekend', models.BooleanField()),
                ('dbSelfEscorts', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceSequence',
            fields=[
                ('dbInvoiceNo', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('dbOwnerCode', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('dbOwner', models.CharField(max_length=100)),
                ('dbOwnerAddr1', models.CharField(max_length=255)),
                ('dbOwnerAddr2', models.CharField(max_length=255)),
                ('dbOwnerAddr3', models.CharField(max_length=255)),
                ('dbTelNo', models.CharField(max_length=20)),
                ('dbCelNo', models.CharField(max_length=20)),
                ('dbOnHold', models.BooleanField()),
                ('dbOnHoldReason', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PBSPermit',
            fields=[
                ('dbPBS_No', models.IntegerField(primary_key=True, serialize=False)),
                ('dbPermitsA', models.CharField(max_length=50)),
                ('dbPermitsIssued', models.CharField(max_length=50)),
                ('dbRegNos', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PermitDist',
            fields=[
                ('RowPosition', models.IntegerField(primary_key=True, serialize=False)),
                ('one_week', models.IntegerField()),
                ('one_month', models.IntegerField()),
                ('two_months', models.IntegerField()),
                ('three_months', models.IntegerField()),
                ('four_months', models.IntegerField()),
                ('five_months', models.IntegerField()),
                ('six_months', models.IntegerField()),
                ('seven_months', models.IntegerField()),
                ('eight_months', models.IntegerField()),
                ('nine_months', models.IntegerField()),
                ('ten_months', models.IntegerField()),
                ('eleven_months', models.IntegerField()),
                ('twelve_months', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PermitProvince',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dbPermitNo', models.IntegerField()),
                ('dbAmendNo', models.IntegerField()),
                ('dbProvCode', models.CharField(max_length=10)),
                ('dbPercentage', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='PermitSequence',
            fields=[
                ('dbSequenceNo', models.IntegerField(primary_key=True, serialize=False)),
                ('dbSequenceDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('dbProvIndex', models.IntegerField(primary_key=True, serialize=False)),
                ('dbProvCode', models.CharField(max_length=10)),
                ('dbProvince', models.CharField(max_length=100)),
                ('dbAVRDownloadDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('dbRouteCode', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('dbRouteStart', models.CharField(max_length=100)),
                ('dbRouteEnd', models.CharField(max_length=100)),
                ('dbRouteDist', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dbHtLimit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dbMassLimit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dbWdthLimit', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='RTIStn',
            fields=[
                ('dbRTIStn', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('dbTelCode', models.CharField(max_length=20)),
                ('dbRTITelNo', models.CharField(max_length=20)),
                ('dbContact', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StatusCode',
            fields=[
                ('dbStatusCode', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('dbStatusDescrip', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('dbPermitNo', models.IntegerField(primary_key=True, serialize=False)),
                ('dbAmendNo', models.IntegerField(blank=True, null=True)),
                ('dbFinYear', models.IntegerField()),
                ('dbProvCode', models.CharField(max_length=10)),
                ('dbCreateTime', models.DateTimeField()),
                ('dbAcceptTime', models.DateTimeField(blank=True, null=True)),
                ('dbIssueTime', models.DateTimeField(blank=True, null=True)),
                ('dbTransactionKey', models.IntegerField()),
                ('dbOperatorCode', models.CharField(max_length=20)),
                ('dbEngineerCode', models.CharField(blank=True, max_length=20, null=True)),
                ('dbAccountCode', models.CharField(max_length=20)),
                ('dbAccountType', models.CharField(max_length=20)),
                ('dbJobNo', models.CharField(blank=True, max_length=50, null=True)),
                ('dbReferenceNo', models.CharField(blank=True, max_length=50, null=True)),
                ('dbOwnerCode', models.CharField(max_length=20)),
                ('dbOwner', models.CharField(max_length=100)),
                ('dbOwnerAddr1', models.CharField(blank=True, max_length=255, null=True)),
                ('dbOwnerAddr2', models.CharField(blank=True, max_length=255, null=True)),
                ('dbOwnerAddr3', models.CharField(blank=True, max_length=255, null=True)),
                ('dbTelCode', models.CharField(blank=True, max_length=10, null=True)),
                ('dbTelNo', models.CharField(blank=True, max_length=20, null=True)),
                ('dbCelNo', models.CharField(blank=True, max_length=20, null=True)),
                ('dbVehType', models.CharField(max_length=50)),
                ('dbLaden', models.BooleanField(default=False)),
                ('dbLdDesc', models.CharField(blank=True, max_length=255, null=True)),
                ('dbLdLen', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dbLdWdth', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dbLdHt', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransQuotePermit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dbQuoteNo', models.IntegerField()),
                ('dbPermitNo', models.IntegerField()),
                ('dbAmendNo', models.IntegerField()),
                ('dbCorrection', models.BooleanField()),
                ('dbAmount', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='TransRegNo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dbPermitNo', models.IntegerField()),
                ('dbAmendNo', models.IntegerField()),
                ('dbVType', models.CharField(max_length=50)),
                ('dbRegNo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('dbApplicationNo', models.IntegerField(primary_key=True, serialize=False)),
                ('dbProvCode', models.CharField(max_length=10)),
                ('dbOperatorCode', models.CharField(max_length=20)),
                ('dbApplicationDate', models.DateTimeField()),
                ('dbTransType', models.IntegerField()),
                ('dbOwnerCode', models.CharField(max_length=20)),
                ('dbPermitType', models.IntegerField()),
                ('dbOriginArea', models.CharField(max_length=100)),
                ('dbDestination', models.CharField(max_length=100)),
                ('dbLoadDesc', models.CharField(max_length=255)),
                ('dbApplicationFee', models.DecimalField(decimal_places=2, max_digits=15)),
                ('dbStatus', models.CharField(max_length=10)),
                ('dbPermitNo', models.IntegerField()),
                ('dbAmendNo', models.IntegerField()),
                ('dbInvoiceNo', models.IntegerField()),
                ('dbAccountCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.account')),
            ],
        ),
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('dbKey', models.AutoField(primary_key=True, serialize=False)),
                ('dbShc', models.BooleanField()),
                ('dbChargeEngFee', models.BooleanField()),
                ('dbCheckCond', models.CharField(max_length=255)),
                ('dbReference', models.CharField(max_length=255)),
                ('dbApplicationNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.application')),
            ],
        ),
        migrations.CreateModel(
            name='AV_Axle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dbVType', models.CharField(max_length=50)),
                ('dbAxMass', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dbActMass', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dbNAxles', models.IntegerField()),
                ('dbAxType', models.IntegerField()),
                ('dbTyrePressure', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dbWheelSpacing', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dbUnladen', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dbMaxPayload', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dbEffWidth', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dbFirstToLast', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dbAVNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.av')),
            ],
        ),
        migrations.CreateModel(
            name='AV_Dimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dbCode', models.CharField(max_length=10)),
                ('dbValue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dbAVNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.av')),
            ],
        ),
        migrations.CreateModel(
            name='EPermit',
            fields=[
                ('dbPermitNo', models.IntegerField(primary_key=True, serialize=False)),
                ('dbAmendNo', models.IntegerField()),
                ('dbProvCode', models.CharField(max_length=10)),
                ('dbPrinted', models.BooleanField()),
                ('dbEMailed', models.BooleanField()),
                ('ePermitGUID', models.CharField(max_length=50)),
                ('dbAccountCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.account')),
            ],
        ),
        migrations.CreateModel(
            name='RouteProvince',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dbProvCode', models.CharField(max_length=10)),
                ('dbPercentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('dbRouteCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.route')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionsAmended',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.transaction')),
            ],
            options={
                'verbose_name': 'Amended Transaction',
                'verbose_name_plural': 'Amended Transactions',
                'db_table': 'transactions_amended',
            },
            bases=('core.transaction',),
        ),
        migrations.CreateModel(
            name='TransactionsCancelled',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.transaction')),
            ],
            options={
                'verbose_name': 'Cancelled Transaction',
                'verbose_name_plural': 'Cancelled Transactions',
                'db_table': 'transactions_cancelled',
            },
            bases=('core.transaction',),
        ),
        migrations.CreateModel(
            name='TransactionsCorrected',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.transaction')),
            ],
            options={
                'verbose_name': 'Corrected Transaction',
                'verbose_name_plural': 'Corrected Transactions',
                'db_table': 'transactions_corrected',
            },
            bases=('core.transaction',),
        ),
        migrations.CreateModel(
            name='TransactionBook',
            fields=[
                ('dbTransactionKey', models.AutoField(primary_key=True, serialize=False)),
                ('dbTransactionDate', models.DateTimeField()),
                ('dbTransactionType', models.CharField(max_length=10)),
                ('dbPaymentMethod', models.CharField(max_length=10)),
                ('dbPermitNo', models.IntegerField()),
                ('dbAmendNo', models.IntegerField()),
                ('dbRemarks', models.CharField(max_length=255)),
                ('dbReceiptNo', models.CharField(max_length=50)),
                ('dbReceiptAmount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('dbReceiptDate', models.DateField()),
                ('dbChequeNo', models.CharField(max_length=50)),
                ('dbAmount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('dbBalance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('dbOwner', models.CharField(max_length=100)),
                ('dbJobNo', models.CharField(max_length=50)),
                ('dbInvoiceNo', models.IntegerField()),
                ('dbAccountCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.account')),
            ],
        ),
        migrations.CreateModel(
            name='TransQuote',
            fields=[
                ('dbQuoteNo', models.IntegerField(primary_key=True, serialize=False)),
                ('dbQuoteDate', models.DateTimeField()),
                ('dbAccountCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.account')),
            ],
        ),
    ]
