# Generated by Django 5.1.5 on 2025-01-17 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('Supervisor', 'Supervisor'), ('Admin', 'Admin'), ('Operator', 'Operator'), ('Engineer', 'Engineer'), ('Auditor', 'Auditor')], max_length=20)),
            ],
        ),
    ]
