name: CI/CD Pipeline for Django Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    # Checkout the code from GitHub
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10' 

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Set up PostgreSQL service
    - name: Set up PostgreSQL
      uses: harmon758/postgresql-action@v2.0.0
      with:
        postgresql version: '17' # Adjust the version as per your setup
        postgresql db: 'abnormalloads_permits'
        postgresql user: 'postgres'
        postgresql password: 'admin'

    # Apply Django migrations
    - name: Run Migrations
      env:
        DATABASE_URL: postgres://postgres:admin@localhost:5432/abnormalloads_permits
      run: python manage.py migrate

    # Run Django tests
    - name: Run Tests
      run: python manage.py test

  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/main' && success()

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    # NOTE!!!! Deploy Step (Replace with actual deployment command)
    - name: Deploy to Production
      run: |
        echo "Deploying to Production..."
        # Example: scp files or trigger a deployment script
        # scp -r ./your_project/ your_user@your_server:/path/to/deploy/
