name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    name: Build, Test, and Lint
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: Run migrations
    - name: Run migrations
      run: python manage.py migrate

    # Step 5: Run tests
    - name: Run tests
      run: python manage.py test

    # Step 6: Lint code with Flake8
    - name: Lint code
      run: pip install flake8 && flake8 .

  build-docker-image:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
    # Step 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 3: Build and push Docker image
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/my_project:latest

  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: build-docker-image

    steps:
    # Step 1: SSH into the production server
    - name: Deploy to Production Server
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.PRODUCTION_SERVER_IP }}
        username: ${{ secrets.PRODUCTION_SERVER_USER }}
        password: ${{ secrets.PRODUCTION_SERVER_PASSWORD }}
        port: ${{ secrets.PRODUCTION_SERVER_PORT }}
        script: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/my_project:latest
          docker stop my_project || true
          docker rm my_project || true
          docker run -d --name my_project -p 8000:8000 ${{ secrets.DOCKER_USERNAME }}/my_project:latest

#(Notes) Secrets Required in GitHub
#-DOCKER_USERNAME: Your Docker Hub username.
#-DOCKER_PASSWORD: Your Docker Hub password.
#-PRODUCTION_SERVER_IP: The IP address of your production server.
#-PRODUCTION_SERVER_USER: The SSH username for the server.
#-PRODUCTION_SERVER_PASSWORD: The SSH password for the server.
#-PRODUCTION_SERVER_PORT: The SSH port (default is 22).

          
